version: "3"

networks:
  web:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: adamgray.us
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    ports:
      - 8000:80
    volumes:
      - ./src:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agray.entrypoints=websecure"
      - "traefik.http.routers.agray.tls=true"
      - "traefik.http.routers.agray.tls.certresolver=http-le"
      - "traefik.http.routers.agray.rule=Host(`www.adamgray.us`) || Host(`adamgray.us`)"
      - "traefik.http.routers.agray.middlewares=chain-no-auth@file"

